export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as HeaderCards} from './HeaderCards'
export {default as Food} from './Food'
export {default as Catagories} from './Catagories'